PPROF_TEMP_FOLDER="pprof/$(date +%Y-%m-%d_%H-%M-%S)"
mkdir -p "${PPROF_TEMP_FOLDER}"
curl localhost:8081/debug/pprof/cmdline -o ${PPROF_TEMP_FOLDER}/cmdline.out || echo "can't download cmdline"
curl localhost:8081/debug/pprof/profile -o ${PPROF_TEMP_FOLDER}/profile.out || echo "can't download profile"
curl localhost:8081/debug/pprof/symbol -o ${PPROF_TEMP_FOLDER}/symbol.out || echo "can't download symbol"
curl localhost:8081/debug/pprof/trace -o ${PPROF_TEMP_FOLDER}/trace.out || echo "can't download trace"
curl localhost:8081/debug/pprof/goroutine -o ${PPROF_TEMP_FOLDER}/goroutine.out || echo "can't download goroutine"
curl localhost:8081/debug/pprof/threadcreate -o ${PPROF_TEMP_FOLDER}/threadcreate.out || echo "can't download threadcreate"
curl localhost:8081/debug/pprof/heap -o ${PPROF_TEMP_FOLDER}/heap.out || echo "can't download heap"
curl localhost:8081/debug/pprof/allocs -o ${PPROF_TEMP_FOLDER}/allocs.out || echo "can't download allocs"
curl localhost:8081/debug/pprof/block -o ${PPROF_TEMP_FOLDER}/block.out || echo "can't download block"
curl localhost:8081/debug/pprof/mutex -o ${PPROF_TEMP_FOLDER}/mutex.out || echo "can't download mutex"
